// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1edG8ohJs9ezruPrZPwgDM042dNxm-oQ',
    appId: '1:1023278964866:web:890e332dfbc2b658a6d49b',
    messagingSenderId: '1023278964866',
    projectId: 'flutterpractices-f6607',
    authDomain: 'flutterpractices-f6607.firebaseapp.com',
    storageBucket: 'flutterpractices-f6607.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpu2NDMphepXZ05qbiSbPHuo7-RqXaO3g',
    appId: '1:1023278964866:android:46e2c2a9f36a5b35a6d49b',
    messagingSenderId: '1023278964866',
    projectId: 'flutterpractices-f6607',
    storageBucket: 'flutterpractices-f6607.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNcE79puFt7WxvV6U_40LbDW1eYLy8PC0',
    appId: '1:1023278964866:ios:482afd386626ee5ca6d49b',
    messagingSenderId: '1023278964866',
    projectId: 'flutterpractices-f6607',
    storageBucket: 'flutterpractices-f6607.firebasestorage.app',
    iosBundleId: 'com.vishalsawant.flutterBlocLab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNcE79puFt7WxvV6U_40LbDW1eYLy8PC0',
    appId: '1:1023278964866:ios:482afd386626ee5ca6d49b',
    messagingSenderId: '1023278964866',
    projectId: 'flutterpractices-f6607',
    storageBucket: 'flutterpractices-f6607.firebasestorage.app',
    iosBundleId: 'com.vishalsawant.flutterBlocLab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1edG8ohJs9ezruPrZPwgDM042dNxm-oQ',
    appId: '1:1023278964866:web:7d820ae66570141ca6d49b',
    messagingSenderId: '1023278964866',
    projectId: 'flutterpractices-f6607',
    authDomain: 'flutterpractices-f6607.firebaseapp.com',
    storageBucket: 'flutterpractices-f6607.firebasestorage.app',
  );
}
